CREATE DATABASE airline;
USE airline;

# Users
CREATE TABLE users (
	id INT NOT NULL AUTO_INCREMENT,
	nome VARCHAR(255) NOT NULL,
	identificacao VARCHAR(9) NOT NULL,
	nif VARCHAR(9) NOT NULL,
	telefone VARCHAR(9) NOT NULL,
	email VARCHAR(255) NOT NULL,
	password VARCHAR(255) NOT NULL,
	isAdmin BOOLEAN NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	updated_at TIMESTAMP NULL,
	PRIMARY KEY (id)
);

# Origem
CREATE TABLE origem (
	id INT NOT NULL AUTO_INCREMENT,
	nome VARCHAR(255) NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	updated_at TIMESTAMP NULL,
	PRIMARY KEY (id)
);

# Destino
CREATE TABLE destino (
	id INT NOT NULL AUTO_INCREMENT,
	nome VARCHAR(255) NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	updated_at TIMESTAMP NULL,
	PRIMARY KEY (id)
);

# Voo
CREATE TABLE voo (
	id INT NOT NULL AUTO_INCREMENT,
	origemId INT NOT NULL,
	destinoId INT NOT NULL,
	nVoo VARCHAR(255) NOT NULL,
	data datetime NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	updated_at TIMESTAMP NULL,
	PRIMARY KEY (id),
	FOREIGN KEY (origemId)  REFERENCES origem(id),
	FOREIGN KEY (destinoId) REFERENCES destino(id)
);

# Reserva
CREATE TABLE reserva (
	id INT NOT NULL AUTO_INCREMENT,
	userId INT NOT NULL,
	vooId INT NOT NULL,
	nReserva VARCHAR(255) NOT NULL,
	valor INT NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	updated_at TIMESTAMP NULL,
	PRIMARY KEY (id),
	FOREIGN KEY (userId) REFERENCES users(id),
	FOREIGN KEY (vooId)  REFERENCES voo(id)
);